# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='upload_images/')),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('vigencia', models.DateField(blank=True, null=True)),
                ('ingredientes_principales', models.CharField(max_length=200)),
                ('ingredientes_personalizables', models.CharField(max_length=200)),
            ],
        ),
    ]
