# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20170513_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ingredientes_personalizables',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
