# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 18:37
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20170513_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ingredientes_personalizables',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'carne de cerdo'), (2, 'lechuga'), (3, 'queso'), (6, 'jamon'), (13, 'Tocineta'), (21, 'pepinillos'), (22, 'jalapeños')], max_length=16),
        ),
    ]
