# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0002_ingrediente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='email',
        ),
    ]
